changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
    authors:
      - dependabot
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Methodology / data
      labels:
        - methodology
        - data
    - title: Internal / chores
      labels:
        - chore
        - refactor
        - ci
    - title: Other changes
      labels:
        - "*"
